### PR TITLE
Play sounds when muting and unmuting

### PR DESCRIPTION
**Pull request by BenignBeppe**
Added playing two different sounds when muting and unmuting to
complement visual feedback. Includes setting to turn this on or off.

### CODE REVIEW

**Comment by wbolster** [comment]
sorry for not paying attention to this for a long time.

this pr is now outdated, and had conflicting files.

File: extension.js [hunk 1]
```diff
@@ -144,6 +160,9 @@ function on_activate({ give_feedback }) {
     if (give_feedback) {
       show_osd(null, false, microphone.level);
     }
+    if(settings.get_boolean("play-feedback-sounds")) {
```
Comment (szpak) [inline extension.js:163]: A nitpicking, but this project seems to use `if<space>(` formatting convention, while you seem to prefer to omit a space character (multiple times). Maybe it would be good to keep the original style?

**Review by szpak — CHANGES_REQUESTED** [review]
Thanks for for your work on that feature. I gave it a try, however, there are some issues with Gnome Shell 41.

I did:
1. Update local extension directory to the Git version from your branch
2. `make` - to (re)compile schema(s)
3. Restart Gnome Shell (ALT-F2 r) - X11
3. Turn on, off, on, off microphone using a keyboard shortcut.

Expected result:

It can see the sound s every time I enable/disable microphone.

Actual result:

I head sound only twice. Once when I turn it on and once when I turn off. After that no sounds are played at all (until I restart Gnome shell).


In addition, there is a problem with the preferences dialog.

> gnome-extensions prefs nothing-to-say@extensions.gnome.wouter.bolsterl.ee 

generates:
image

with the following in the system logs:
```
gjs[16243]: Some code accessed the property 'KeybindingsWidget' on the module 'keybindingsWidget'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
gjs[16243]: JS ERROR: Failed to open preferences: Error: No property margin on GtkGrid
    _init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:45:40
    buildPrefsWidget@/home/foobar/.local/share/gnome-shell/extensions/nothing-to-say@extensions.gnome.wouter.bolsterl.ee/prefs.js:18:23
    _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:219:40
    OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:128:33
    asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
    run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
    main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
                                   run@resource:///org/gnome/gjs/modules/script/package.js:206:19
                                   start@resource:///org/gnome/gjs/modules/script/package.js:190:8
                                   @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by BenignBeppe** [comment]
Thanks for testing on Gnome 41, @szpak. I hope the patches fix the settings crash. I'll have to look into why sound only play once. Maybe something with the rewind not working anymore on newer Gnome.

**Comment by BenignBeppe** [comment]
I found another way to rewind the sound before playing. Can you try if this works?

**Comment by szpak** [comment]
> I found another way to rewind the sound before playing. Can you try if this works?

It works fine with 41 (both sounds and preferences), nice!

There is just one warning in the logs:
> gjs[23110]: JS WARNING: [/home/foobar/.local/share/gnome-shell/extensions/nothing-to-say@extensions.gnome.wouter.bolsterl.ee/prefs.js 47]: Too many arguments to method Gtk.ListBox.append: expected 1, got 2

**Comment by BenignBeppe** [comment]
Realised I didn't add a comment for this. The warning should be gone now. I tried to do the pushing the way git told me to and it resulted in a lot of duplicated commits. The changes should still be good though and a squash merge should clean it up. Still haven't gotten the hang of the Github review process :/

**Review by szpak — APPROVED** [review]
Works fine with Gnome Shell 40.8.

**Comment by wbolster** [comment]
thanks all! just published a new version including these changes

**Comment by wbolster** [comment]
the .zip uploaded to the extension website was missing the sound files 🙉 

fixed via 5b6f3a14ba44b277793b3e17ea5580d01628fcc3; uploaded a new version already

**Comment by BenignBeppe** [comment]
Good, I didn't notice this until I was on a different machine🙂
